AWSTemplateFormatVersion: "2010-09-09"
Resources:
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Origins:
          - Id: S3Origin
            DomainName: "{{UI_BUCKET}}.s3.amazonaws.com"
            OriginAccessControlId: "{{OAC_ID}}"
            S3OriginConfig: {}
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          Compress: true
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
        DefaultRootObject: index.html
        HttpVersion: http2
        PriceClass: PriceClass_100
        Restrictions:
          GeoRestriction:
            RestrictionType: none
        Comment: CloudFront distribution for {{UI_BUCKET}} with OAC
Outputs:
  CloudFrontDistributionId:
    Value: !Ref CloudFrontDistribution
    Description: The ID of the CloudFront distribution
